### ISSUE TITLE
I can't see any of my tasks.

### ISSUE THREAD

**Issue by joshmccord** [jahdaic/WunderPebble#1]
I just got a Pebble today and while the app looks nice it won't load any tasks from any of my lists, just a blank screen (bottom 2/3 is white, top 1/3 is black). I don't know what other information I can post to help diagnose it but I'm using an iPhone 6 and have Wunderlist Pro.

**Comment by jahdaic** [comment]
I have rewritten this app using Pebble.js and this one is no longer maintained. I already submitted it to the Pebble App Store, but it will probably take a while for it to show up in iOS, since Pebble has update their app to include new JavaScript.

In the mean time you can check out the new code at: https://github.com/jahdaic/WunderPebbleJS
and download the latest version of the watch app at: https://builds.cloudpebble.net/55ad6d04-d11b-438c-b4f9-9a08fc636e6e/watchface.pbw
